// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_TabPage3 = NULL;
lv_obj_t * ui_TabPage4 = NULL;
lv_obj_t * ui_TabPage5 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_Switch2 = NULL;
// event funtions
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen2, LV_DIR_TOP, 30);
    lv_obj_set_width(ui_TabView1, 240);
    lv_obj_set_height(ui_TabView1, 320);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &ui_font_monkey_6,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Title 2");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Title 3");

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "Title 4");

    ui_TabPage5 = lv_tabview_add_tab(ui_TabView1, "Title 5");

    ui_ImgButton2 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1563899303, NULL);
    lv_obj_set_width(ui_ImgButton2, 38);
    lv_obj_set_height(ui_ImgButton2, 38);
    lv_obj_set_x(ui_ImgButton2, 92);
    lv_obj_set_y(ui_ImgButton2, -106);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Switch2 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch2, 30);
    lv_obj_set_height(ui_Switch2, 14);
    lv_obj_set_x(ui_Switch2, 96);
    lv_obj_set_y(ui_Switch2, -66);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage2 = NULL;
    ui_TabPage3 = NULL;
    ui_TabPage4 = NULL;
    ui_TabPage5 = NULL;
    ui_ImgButton2 = NULL;
    ui_Switch2 = NULL;

}
