// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * gaugepointer_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_898859503);    // assets/profile-removebg-preview.png
LV_IMG_DECLARE(ui_img_1563899303);    // assets/image-removebg-preview (16) (3).png

// FONTS
LV_FONT_DECLARE(ui_font_antasilla_24);
LV_FONT_DECLARE(ui_font_broken_12);
LV_FONT_DECLARE(ui_font_bronken);
LV_FONT_DECLARE(ui_font_bruce_forever_39);
LV_FONT_DECLARE(ui_font_monkey_18);
LV_FONT_DECLARE(ui_font_monkey_6);
LV_FONT_DECLARE(ui_font_upperlock_20);
LV_FONT_DECLARE(ui_font_upper_clock_15);
LV_FONT_DECLARE(ui_font_upper_clock_18);
LV_FONT_DECLARE(ui_font_upper_clock_22);
LV_FONT_DECLARE(ui_font_upper_clock_40);
LV_FONT_DECLARE(ui_font_upper_clock_55);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
